--- 
  - name: Update
    apt:
      update_cache: yes
  - name: Install curl and others
    apt:
      name: 
        - curl
        - software-properties-common
        - ca-certificates
        - apt-transport-https
      state: present
      update_cache: yes