apiVersion: 1
providers:
  - name: 'Node Exporter Full'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    updateIntervalSeconds: 60
    options:
      path: /etc/grafana/provisioning/dashboards/dashboards_data/